#!/usr/bin/env python
# coding=utf-8

import sys, pyperclip, pprint

FACES = {
    'laugh cry': '😂',
    'smug': '😏',
    'wink': '😉',
    'wink tongue': '😜',
    'XD': '😆',
    'frown': '🙁'
}

def getFace(t):
    return FACES.get(t, '😊')

# Run ----------------------------
face = None
if len(sys.argv) > 1:
    face = " ".join(sys.argv[1:])
print getFace(face)

if face == "help":
    for k,v in FACES.iteritems():
        print k.ljust(max(map(len, FACES))) + " | " + v

pyperclip.copy(getFace(face))
