#!/usr/bin/env python
# coding=utf-8

import sys, pyperclip, pprint

FACES = {
    'smug': '😏',
    'wink': '😉',
    'wink tongue': '😜',
    'XD': '😆',
    'frown': '🙁'
}

def getFace(t):
    return FACES.get(t, '😊')

# Run ----------------------------
face = None
if len(sys.argv) > 1:
    face = " ".join(sys.argv[1:])

if face == "help":
	pprint.pprint(FACES)

pyperclip.copy(getFace(face))
